KCL_TYPES = {
    'Road': ['Normal', 'Dirt, GFX on slots 7.3 and 8.3', 'Gravel/Stone', 'Smooth', 'Wood', 'Snow with GFX',
             'Metal Grate', 'Normal, but sound cuts off'],
    'Slippery Road 1': ['White Sand', 'Dirt', 'Water', 'Snow', 'Grass', 'Yellow Sand',
                        'Sand, no GFX', 'Dirt, no GFX'],
    'Weak Off-Road': ['Orange Sand', 'Dirt', 'Water', 'Grass, darker GFX', 'Sand, lighter GFX', 'Carpet',
                      'Gravel', 'Gravel, different impact SFX'],
    'Off-Road': ['Sand', 'Dirt', 'Mud', 'Water, no GFX', 'Grass', 'Sand, lighter GFX',
                 'Gravel, different impact SFX', 'Carpet'],
    'Heavy Off-Road': ['Sand', 'Dirt', 'Mud', 'Flowers', 'Grass', 'Snow', 'Sand', 'Dirt, no GFX'],
    'Slipppery Road 2': ['Ice', 'Mud', 'Water', 'Normal road, different sound'],
    'Boost Pad': ['Default',
                  'If used and casino_roulette is nearby, the road rotates everything around counter-clockwise',
                  'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    'Boost Ramp': ['2 Flips', '1 Flip', 'No flips'],
    'Jump Pad': ['Stage 2, GBA BC3', 'Stage 3, SNES GV2', 'Stage 1, GBA SGB', 'Stage 4, MG',
                 'Stage 5, Bouncy Mushroom', 'Stage 4, Chain Chomp Wall', 'Stage 2, DS YF and Funky Stadium',
                 'Stage 4, unused'],
    'Item Road': ['Unknown', 'Unknown', 'Used on metaal grates', 'Used on wooden paths/grass/mushrooms',
                  'Unknown', 'Used on grass/bushes', 'Unknown'],
    'Solid Fall': ['Sand', 'Underwater', 'Unknown', 'Ice', 'Dirt', 'Grass', 'Wood', 'Unknown'],
    'Moving Road': ['Water following route', 'Water following route, pulls player downwards',
                    'Water following route, pulls player', 'Moving water no route, pulls player down',
                    'Moving asphalt', 'Moving asphalt', 'Moving road', 'Unknown'],
    'Wall': ['Normal', 'Rock', 'Metal', 'Wood', 'Ice', 'Bush', 'Rope', 'Rubber'],
    'Invisible Wall': ['No spark and SFX', 'Spark and SFX', 'Spark and SFX', 'Unknown', 'Unknown',
                       'Unknown', 'Unknown', 'Unknown'],
    'Item Wall': ['Unknown', 'Unknown, used on rock walls', 'Unknown, used on metal walls', 'Unknown', 'Unknown',
                  'Unknown, used on grass/bushes', 'Unknown'],
    'Wall 3': ['Normal', 'Rock', 'Metal', 'Wood', 'Ice', 'Bush', 'Rope', 'Rubber'],
    'Fall Boundary': ['Air Fall', 'Water, setting 1 refers to index in KMP', 'Lava, setting 1 refers to index in KMP',
                      'Icy Water, setting 1 refers to index in KMP (6.1)', 'Lava, no GFX', 'Burning Air Fall',
                      'Quicksand', 'Short Fall'],
    'Cannon Activator': ['Point 0', 'Point 1', 'Point 2', 'Point 3', 'Point 4', 'Point 5', 'Point 6', 'Point 7'],
    'Force Recalculation': ['Recalculation 0', 'Recalculation 1', 'Recalculation 2', 'Recalculation 3',
                            'Recalculation 4', 'Recalculation 5', 'Recalculation 6', 'Recalculation 7'],
    'Half-Pipe Ramp': ['Default', 'Boost pad applied, used in Bowsers Castle', 'Unknown', 'Unknown', 'Unknown',
                       'Unknown', 'Unknown', 'Unknown'],
    'Wall 2': ['Normal', 'Rock', 'Metal', 'Wood', 'Ice', 'Bush', 'Rope', 'Rubber'],
    'Moving Road 2': ['Moves west with BeltCrossing and escalator',
                      'Moves east with BeltCrossing and west with escalator.',
                      'Moves east with BeltEasy', 'Moves west with BeltEasy', 'Rotates around BeltCurveA clockwise',
                      'Rotates around BeltCurveA counterclockwise'],
    'Gravity Road': ['Wood', 'Gravel, different impact SFX', 'Carpet', 'Dirt, no GFX',
                     'Sand, different impact and drift SFX, no GFX',
                     'Normal Road, SFX on 4.4', 'Normal road', 'Mud with GFX'],
    'Road 2': ['Normal road, different sound', 'Carpet', 'Grass, GFX on 8.3', 'Normal road, used on green mushrooms',
               'Grass', 'Glass road with SFX', 'Dirt', 'Normal Road, SFX on 4.4'],
    'Sound Trigger': ['Sound Trigger 0', 'Sound Trigger 1', 'Sound Trigger 2', 'Sound Trigger 3', 'Sound Trigger 4',
                      'Sound Trigger 5', 'Sound Trigger 6', 'Sound Trigger 7'],
    'Unknown': ['Unknown'] * 8,
    'Effect Trigger': ['BRSTM reset', 'Enable Shadow Effect', 'Water Splash', 'Stargate Activation',
                       'Unknown', 'Unknown', 'Unknown', 'Unknown'],
    'Unknown 2': ['Unkown'] * 8,
    'Half-pipe Invisible Wall': ['Unkown'] * 8,
    'Moving Road 3': ['Carpet, different impact SFX', 'Normal Road, different sound', 'Normal Road', 'Glass Road',
                      'Carpet', 'No sound, star crash impact SFX (requires starGate)', 'Sand', 'Dirt'],
    'Special Walls': ['Cacti effect', 'Fast:bump (rubber wall)', 'Fast:spark, hollow, bump, slow:many bumps',
                      'Fast:bump',
                      'Fast:spark, bump, SFX on 4.4', 'Fast:spark, cracking, bump', 'Fast:spark, metal, bump',
                      'Fast:spark, Star Ring crash, bump, Slow:Star Ring crash'],
    'Player Wall': ['Fast Bump'] * 8
}

KCL_KEYS = [
    'Road', 'Slippery Road 1', 'Weak Off-Road', 'Off-Road', 'Heavy Off-Road', 'Slipppery Road 2', 'Boost Pad',
    'Boost Ramp', 'Jump Pad', 'Item Road', 'Solid Fall', 'Moving Road', 'Wall', 'Invisible Wall', 'Item Wall',
    'Wall 3', 'Fall Boundary', 'Cannon Activator', 'Force Recalculation', 'Half-Pipe Ramp', 'Wall 2',
    'Moving Road 2', 'Gravity Road', 'Road 2', 'Sound Trigger', 'Unknown', 'Effect Trigger', 'Unknown 2',
    'Half-pipe Invisible Wall', 'Moving Road 3', 'Special Walls', 'Player Wall'
]
